import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Homepage from '@/containers/Homepage'
import Card from '@/utils/Card'
import Collections from '@/components/Collections'
import Popularplaces from '@/components/Popularplaces'
import GetApp from '@/components/GetApp'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Zomato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
       <Homepage />
       <main className='md:max-w-[80%] md:mx-auto'>
          <div className='grid grid-cols-2 md:grid-cols-3'>
            <Card/>
            <Card/>
            <Card/>
          </div>
          <Collections/>  
          <Popularplaces/>
       </main>
       <GetApp/>
       
    </>
  )
}
