import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Homepage from '@/containers/Homepage'
import Card from '@/utils/Card'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Homepage />
       <main>
          <div className='grid grid-cols-2 md:grid-cols-3'>
            <Card/>
            <Card/>
            <Card/>
          </div>
       </main>
       
    </>
  )
}
